server:
  port: 8082

spring:
  application:
    name: cities-service
  cloud:
    discovery:
      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka
