server:
  port: 8083
spring:
  application:
    name: hotels-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/config-repo
          search-paths: submodules/config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
